apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-load-balancers-describe
version: 1
summary: Describe load balancers
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-load-balancers-describe

examples:
- summary: Describe the load balancers in an AWS account
  content:
    apiVersion: 1
    kind: Step
    name: elbv2-describe-load-balancers
    image: relaysh/aws-elbv2-step-load-balancers-describe
    spec:
      aws:
        connection: !Connection { type: aws, name: my-aws-account }
        region: !Parameter awsRegion
