apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-targets-describe
version: 1
summary: Describe targets
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-targets-describe

examples:
- summary: Describe targets from a target group in an AWS account
  content:
    apiVersion: v1
    kind: Step
    name: elbv2-describe-targets
    image: relaysh/aws-elbv2-step-targets-describe
    spec:
      aws:
        connection: !Connection { type: aws, name: my-aws-account }
        region: !Parameter awsRegion
      targetgroups: 
      - !Parameter targetGroupArn
