apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-targets-describe
version: 1
summary: Describe targets
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-targets-describe
