apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-target-groups-describe
version: 1
summary: Describe target groups
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-target-groups-describe

examples:
- summary: Describe target groups in an AWS account
  content:
    apiVersion: v1
    kind: Step
    name: elbv2-describe-target-groups
    image: relaysh/aws-elbv2-step-target-groups-describe
    spec:
      aws:
        connection: !Connection { type: aws, name: my-aws-account }
        region: !Parameter awsRegion
