apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-load-balancers-delete
version: 1
summary: Delete load balancers
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-load-balancers-delete

examples:
- summary: Delete a single load balancer from an AWS account
  content:
    apiVersion: 1
    kind: Step
    name: elbv2-delete-load-balancers
    image: relaysh/aws-elbv2-step-load-balancers-delete
    spec:
      aws:
        connection: !Connection {type: aws, name: my-aws-account}
        region: !Parameter awsRegion
      loadbalancerARNs:
      - !Parameter loadBalancerArn