apiVersion: integration/v1
kind: Step
name: aws-elbv2-step-load-balancers-delete
version: 1
summary: Delete load balancers
description: |
icon:
schemas:
  spec:
    source: file
    file: spec.schema.json
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/aws-elbv2-step-load-balancers-delete
